/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("list_items").del();
  await knex("list_items").insert([
    {
      id: 1,
      text: "Call school",
      done: 0,
      list_id: 1,
    },
    {
      id: 2,
      text: "Complete project report",
      done: 0,
      list_id: 1,
    },
    {
      id: 3,
      text: "Renew gym membership",
      done: 0,
      list_id: 3,
    },
    {
      id: 4,
      text: "Attend team meeting",
      done: 0,
      list_id: 4,
    },
    {
      id: 5,
      text: "Submit quarterly taxes",
      done: 0,
      list_id: 5,
    },
    {
      id: 6,
      text: "Plan family reunion",
      done: 0,
      list_id: 6,
    },
    {
      id: 7,
      text: "Review annual budget",
      done: 0,
      list_id: 7,
    },
    {
      id: 8,
      text: "Schedule dentist appointment",
      done: 0,
      list_id: 8,
    },
    {
      id: 9,
      text: "Organize charity event",
      done: 0,
      list_id: 9,
    },
    {
      id: 10,
      text: "Revise marketing strategy",
      done: 0,
      list_id: 10,
    },
    {
      id: 11,
      text: "Prepare for board meeting",
      done: 0,
      list_id: 11,
    },
    {
      id: 12,
      text: "Arrange team-building activities",
      done: 0,
      list_id: 12,
    },
    {
      id: 13,
      text: "Plan holiday celebration",
      done: 0,
      list_id: 13,
    },
    {
      id: 14,
      text: "Write weekly blog post",
      done: 0,
      list_id: 14,
    },
    {
      id: 15,
      text: "Research new technology trends",
      done: 0,
      list_id: 15,
    },
    {
      id: 16,
      text: "Create presentation slides",
      done: 0,
      list_id: 16,
    },
    {
      id: 17,
      text: "Practice meditation",
      done: 0,
      list_id: 17,
    },
    {
      id: 18,
      text: "Learn a new language",
      done: 0,
      list_id: 18,
    },
    {
      id: 19,
      text: "Start workout routine",
      done: 0,
      list_id: 19,
    },
    {
      id: 20,
      text: "Read a book",
      done: 0,
      list_id: 20,
    },
    {
      id: 21,
      text: "Buy groceries",
      done: 0,
      list_id: 21,
    },
    {
      id: 22,
      text: "Complete project report",
      done: 0,
      list_id: 22,
    },
    {
      id: 23,
      text: "Renew gym membership",
      done: 0,
      list_id: 23,
    },
    {
      id: 24,
      text: "Attend team meeting",
      done: 0,
      list_id: 4,
    },
    {
      id: 25,
      text: "Submit quarterly taxes",
      done: 0,
      list_id: 25,
    },
    {
      id: 26,
      text: "Plan family reunion",
      done: 0,
      list_id: 26,
    },
    {
      id: 27,
      text: "Review annual budget",
      done: 0,
      list_id: 27,
    },
    {
      id: 28,
      text: "Schedule dentist appointment",
      done: 0,
      list_id: 28,
    },
    {
      id: 29,
      text: "Organize charity event",
      done: 0,
      list_id: 29,
    },
    {
      id: 30,
      text: "Revise marketing strategy",
      done: 0,
      list_id: 30,
    },
    {
      id: 31,
      text: "Prepare for board meeting",
      done: 0,
      list_id: 31,
    },
    {
      id: 32,
      text: "Arrange team-building activities",
      done: 0,
      list_id: 32,
    },
    {
      id: 33,
      text: "Plan holiday celebration",
      done: 0,
      list_id: 33,
    },
    {
      id: 34,
      text: "Write weekly blog post",
      done: 0,
      list_id: 34,
    },
    {
      id: 35,
      text: "Research new technology trends",
      done: 0,
      list_id: 35,
    },
    {
      id: 36,
      text: "Create presentation slides",
      done: 0,
      list_id: 36,
    },
    {
      id: 37,
      text: "Practice meditation",
      done: 0,
      list_id: 37,
    },
    {
      id: 38,
      text: "Learn a new language",
      done: 0,
      list_id: 38,
    },
    {
      id: 39,
      text: "Start workout routine",
      done: 0,
      list_id: 39,
    },
    {
      id: 40,
      text: "Read a book",
      done: 0,
      list_id: 4,
    },
    {
      id: 41,
      text: "Bananas",
      done: 0,
      list_id: 1,
    },
    {
      id: 42,
      text: "Pasta",
      done: 0,
      list_id: 1,
    },
    {
      id: 43,
      text: "Pasta sauce",
      done: 0,
      list_id: 1,
    },
    {
      id: 44,
      text: "Lemon juice",
      done: 0,
      list_id: 1,
    },
    {
      id: 45,
      text: "Chicken wings",
      done: 0,
      list_id: 1,
    },
    {
      id: 46,
      text: "Baked beans",
      done: 0,
      list_id: 1,
    },
    {
      id: 47,
      text: "Lettuce",
      done: 0,
      list_id: 1,
    },
    {
      id: 48,
      text: "Rice",
      done: 0,
      list_id: 1,
    },
    {
      id: 49,
      text: "Peppers",
      done: 0,
      list_id: 1,
    },
    {
      id: 50,
      text: "Tomatoes",
      done: 0,
      list_id: 1,
    },
    {
      id: 51,
      text: "Cucumber",
      done: 0,
      list_id: 1,
    },
    {
      id: 52,
      text: "Fix door",
      done: 0,
      list_id: 2,
    },
    {
      id: 53,
      text: "Get new fridge",
      done: 0,
      list_id: 2,
    },
    {
      id: 54,
      text: "Get rid of buggy",
      done: 0,
      list_id: 2,
    },
    {
      id: 55,
      text: "Buy coal",
      done: 0,
      list_id: 2,
    },
    {
      id: 56,
      text: "Get newspapers",
      done: 0,
      list_id: 2,
    },
  ]);
};
