/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("list_items").del();
  await knex("list_items").insert([
    {
      id: 1,
      text: "Buy groceries",
      done: 1,
      list_id: 1,
    },
    {
      id: 2,
      text: "Capstone project",
      done: 1,
      list_id: 1,
    },
    {
      id: 3,
      text: "Call GP",
      done: 0,
      list_id: 1,
    },
    {
      id: 4,
      text: "Get coal",
      done: 0,
      list_id: 1,
    },
    {
      id: 5,
      text: "Plan holidays",
      done: 0,
      list_id: 1,
    },
    {
      id: 6,
      text: "Gift for dad",
      done: 1,
      list_id: 1,
    },
    {
      id: 7,
      text: "Fix stove",
      done: 1,
      list_id: 2,
    },
    {
      id: 8,
      text: "Fix door",
      done: 0,
      list_id: 2,
    },
    {
      id: 9,
      text: "Paint kitchen",
      done: 1,
      list_id: 2,
    },
    {
      id: 10,
      text: "Get new ash bin",
      done: 0,
      list_id: 2,
    },
    {
      id: 11,
      text: "Sort bathroom drawers",
      done: 0,
      list_id: 2,
    },
    {
      id: 12,
      text: "Get new shower curtains",
      done: 0,
      list_id: 2,
    },
    {
      id: 13,
      text: "Plan pic-nic",
      done: 0,
      list_id: 3,
    },
    {
      id: 14,
      text: "Get new light bulbs",
      done: 0,
      list_id: 3,
    },
    {
      id: 15,
      text: "Get plant for bedroom",
      done: 0,
      list_id: 3,
    },
    {
      id: 16,
      text: "Sort out old clothes",
      done: 0,
      list_id: 3,
    },
    {
      id: 17,
      text: "Look up meditation apps",
      done: 0,
      list_id: 3,
    },
    {
      id: 18,
      text: "Scarf",
      done: 0,
      list_id: 4,
    },
    {
      id: 19,
      text: "Tablet",
      done: 1,
      list_id: 4,
    },
    {
      id: 20,
      text: "Socks",
      done: 1,
      list_id: 4,
    },
    {
      id: 21,
      text: "Perfume",
      done: 0,
      list_id: 5,
    },
    {
      id: 22,
      text: "Candles",
      done: 0,
      list_id: 5,
    },
    {
      id: 23,
      text: "Spa voucher",
      done: 1,
      list_id: 5,
    },
    {
      id: 24,
      text: "Bathbombs",
      done: 1,
      list_id: 6,
    },
    {
      id: 25,
      text: "Chocolates",
      done: 1,
      list_id: 6,
    },
    {
      id: 26,
      text: "Blender",
      done: 1,
      list_id: 6,
    },
    {
      id: 27,
      text: "All the light we cannot see",
      done: 0,
      list_id: 8,
    },
    {
      id: 28,
      text: "Milkman",
      done: 0,
      list_id: 8,
    },
    {
      id: 29,
      text: "The dinner gest",
      done: 0,
      list_id: 8,
    },
    {
      id: 30,
      text: "The enchanted life",
      done: 1,
      list_id: 8,
    },
    {
      id: 31,
      text: "Fight Club",
      done: 1,
      list_id: 9,
    },
    {
      id: 32,
      text: "Titanic",
      done: 0,
      list_id: 9,
    },
    {
      id: 33,
      text: "Inglourious Basterds",
      done: 1,
      list_id: 9,
    },
    {
      id: 34,
      text: "Catch Me If You Can",
      done: 0,
      list_id: 9,
    },
    {
      id: 35,
      text: "Mo",
      done: 1,
      list_id: 10,
    },
    {
      id: 36,
      text: "Derry Girls",
      done: 1,
      list_id: 10,
    },
    {
      id: 37,
      text: "Lupin",
      done: 1,
      list_id: 10,
    },
    {
      id: 38,
      text: "Russian Doll",
      done: 0,
      list_id: 10,
    },
    {
      id: 39,
      text: "Top Boy",
      done: 0,
      list_id: 10,
    },
    {
      id: 40,
      text: "Gentefied",
      done: 1,
      list_id: 10,
    },
    {
      id: 41,
      text: "Stranger Things",
      done: 0,
      list_id: 10,
    },
    {
      id: 42,
      text: "Sweet Tooth",
      done: 1,
      list_id: 10,
    },
    {
      id: 43,
      text: "Aasdf",
      done: 0,
      list_id: 11,
    },
    {
      id: 44,
      text: "Qqwer",
      done: 1,
      list_id: 11,
    },
    {
      id: 45,
      text: "Oksjdf",
      done: 1,
      list_id: 11,
    },
    {
      id: 46,
      text: "Lasdf",
      done: 1,
      list_id: 11,
    },
    {
      id: 47,
      text: "Gasddd",
      done: 1,
      list_id: 12,
    },
    {
      id: 48,
      text: "Rirtuy",
      done: 1,
      list_id: 12,
    },
    {
      id: 49,
      text: "Prtytr",
      done: 0,
      list_id: 12,
    },
    {
      id: 50,
      text: "Tthrty",
      done: 0,
      list_id: 13,
    },
    {
      id: 51,
      text: "Crthsdf",
      done: 1,
      list_id: 13,
    },
    {
      id: 52,
      text: "Fyuietgh",
      done: 0,
      list_id: 14,
    },
    {
      id: 53,
      text: "Gukfgj",
      done: 1,
      list_id: 15,
    },
    {
      id: 54,
      text: "Ydfdfbdfxb",
      done: 0,
      list_id: 15,
    },
    {
      id: 55,
      text: "Bujergf",
      done: 1,
      list_id: 15,
    },
    {
      id: 56,
      text: "Gasdfadsf",
      done: 1,
      list_id: 15,
    },
  ]);
};
